name: Check for Print Statements

on:
  pull_request:
    branches:
      - main

jobs:
  check-print-statements:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch the full repository history

      - name: Fetch main branch
        run: git fetch origin main  # Ensure 'origin/main' is available for comparison

      - name: List Python files with print statements
        run: |
          # List all modified Python files in the pull request
          git diff --name-only origin/main...HEAD | grep -E '\.py$' > changed_files.txt || true

          # Check for print statements in those files
          if grep -q 'print(' $(cat changed_files.txt); then
            echo "Error: Found 'print' statements in Python files:"
            grep -Hn 'print(' $(cat changed_files.txt)
            exit 1
          else
            echo "No 'print' statements found. Good to go!"
          fi
